server.port=8081
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html 
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=file:/home/wangweiji/dev/code/springboot_vite_starter/frontend/dist/
spring.web.resources.static-locations=file:/home/wangweiji/dev/code/springboot_vite_starter/frontend/dist/
spring.thymeleaf.suffix=.html