server.port=8080
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html 
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:/home/wangweiji/dev/code/springboot_vite_starter/frontend/src/
spring.web.resources.static-locations=file:/home/wangweiji/dev/code/springboot_vite_starter/frontend/src/
spring.thymeleaf.suffix=.html